### PR TITLE
ci: migrate off travis

### LINKED ISSUE #14: Migrate CI to GitHub Actions
Now that Travis CI has ended their free tier, CI should migrate to GitHub Actions. [The `actions-rs` quickstart example](https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md) is probably a good place to start.

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #14

action runs are in here, https://github.com/chenrui333/rustfilt/actions/workflows/main.yml

cc @luser

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @luser

**Comment by luser** [comment]
This looks fine. If you rebase atop latest master I will merge it. Thanks!

**Comment by chenrui333** [comment]
rebased to the latest master cc @luser sorry about the delay :)

**Comment by luser** [comment]
Not your fault, it took me several months to acknowledge your PR in the first place! Thanks!

**Pull request merged**
