### PR TITLE
Add support for RFC2603 v0 mangled symbols.

### PR DESCRIPTION
**Pull request by jsgf**

### CODE REVIEW

**Comment by luser** [comment]
Heh, I failed to merge https://github.com/luser/rustfilt/pull/10 in a timely manner. :) Your patches are very similar but there are minor differences. I'm not up to speed on the new mangling scheme--is there anything that looks important in the differences between the two?

**Comment by jsgf** [comment]
Oh, I should have checked. But I don't think https://github.com/luser/rustfilt/pull/10 is correct - `_R` symbols don't necessarily start with `_RN`.

**Comment by cuviper** [comment]
It would be nice to also test mangled varieties other than `_RN`.

**Comment by luser** [comment]
Thanks! @cuviper apologies for not getting to your PR sooner!

**Pull request merged**
